### ISSUE TITLE
Kanban Board Submission

### ISSUE THREAD

**Issue by aamir-asaram** [aamir-asaram/RecipEasy#12]
**There are two members working on this ROR group project:**

- @aamir-asaram 
- @hassanShakur 

This is the link to our [Kanban Board](https://github.com/aamir-asaram/RecipEasy/projects/1)

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job creating the board as requested

## Required Changes ♻️
- [ ] to make sure you are complying with the requirement please at least create a card for each bullet point in the requirements list:

![image](https://github.com/aamir-asaram/RecipEasy/assets/39240820/698bb7e2-c573-4fa7-bbfb-580ba22daced)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aamir-asaram** [comment]
@mikethreels should there be a card for each main bullet point (just the dark ones) or for **all** of them? (separate card for each lighter bulltet)

**Comment by mikethreels** [comment]
@aamir-asaram one card for each main bullet should be enough, just make sure to add the lighter bullet to the description.

**Comment by aamir-asaram** [comment]
Noted. Thanks for clarifying @mikethreels :smile:

**Comment by DammyShittu** [comment]
Hi @aamir-asaram and @hassanShakur,

## APPROVED 🟢

## Highlights
✔️ Descriptive issue and tasks

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
